### ISSUE TITLE
关于pnpm-lock.yaml生产

### ISSUE THREAD

**Issue by wjjhhh** [MrWeilian/much-more-design#1]
请问下，每个子包里的【pnpm-lock.yaml】是怎么出来的，是在相应目录下安装生成的吗？
因为我一般是在跟目录操作安装依赖的，只有在根目录有一个【pnpm-lock.yaml】

**Comment by MrWeilian** [comment]
哈喽你好，关于你说的这个现象是我这个项目开启了 `shared-workspace-lockfile=false` 引起的。至于为什么搞这个配置，详细可以看我写的[文章](https://juejin.cn/post/7120893568553582622#heading-17)，其中第五节的第1点有解释原因。

**Comment by MrWeilian** [comment]
> 请问下，每个子包里的【pnpm-lock.yaml】是怎么出来的，是在相应目录下安装生成的吗？ 因为我一般是在跟目录操作安装依赖的，只有在根目录有一个【pnpm-lock.yaml】

我刚自己测试了一下，如果不配置这个属性就只会在根目录有 `lock` 文件

**Comment by wjjhhh** [comment]
> 哈喽你好，关于你说的这个现象是我这个项目开启了 `shared-workspace-lockfile=false` 引起的。至于为什么搞这个配置，详细可以看我写的[文章](https://juejin.cn/post/7120893568553582622#heading-17)，其中第五节的第1点有解释原因。

感谢，学习了
