### ISSUE TITLE
这个正则匹配结果为null？

### ISSUE THREAD

**Issue by mindspark-xin** [MrWeilian/much-more-design#6]
![1712657242558](https://github.com/MrWeilian/much-more-design/assets/134568582/70913148-e9a4-4f08-90ee-b5383cab4b3a)

**Comment by mindspark-xin** [comment]
找到原因了！
Windows通常使用\r\n，而Unix/Linux/macOS使用\n。如果你的文本来自Windows环境而你的正则表达式只匹配\n，那么它可能无法正确匹配。尝试将正则表达式中的(?=\n)改为(?=\r?\n)以兼容两种换行符。

**Comment by MrWeilian** [comment]
厉害了老哥。我正则都是找gpt写的
